package com.gmproxy.Entities;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.room.ColumnInfo;
import androidx.room.Embedded;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Ignore;
import androidx.room.Junction;
import androidx.room.PrimaryKey;
import androidx.room.Relation;

import java.io.Serializable;
import java.util.List;

/**
 * It's your trusty old entity class. It's not much, but it does what it has to do.
 * Some of these you'll see with two constructors. This is due to not having to insert a id since it's autogenerated.
 */
@Entity(tableName = "alarmas_usuarios", foreignKeys = {@ForeignKey(entity = Alarm.class,
                parentColumns = "id_alarma", childColumns = "id_alarma"),
                @ForeignKey(entity = User.class, parentColumns = "id_usuario", childColumns = "id_usuario")})
public class AlarmUser implements Serializable {

    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id_alarma_usuario")
    int id_user_alarm;

    @ColumnInfo(name = "id_alarma")
    Integer id_alarm = 0;

    @ColumnInfo(name = "id_usuario")
    Integer id_user = 0;

    public class AlarmsWithUsers{
        @Embedded public Alarm alarm;
        @Relation (
                parentColumn = "id_alarm",
                entityColumn = "id_user",
                associateBy = @Junction(AlarmUser.class)
        ) public List<User> users;
    }

    public class UsersWithAlarm{
        @Embedded public User users;
        @Relation (
                parentColumn = "id_user",
                entityColumn = "id_alarm",
                associateBy = @Junction(AlarmUser.class)
        ) public List<Alarm> alarms;
    }

    @Ignore
    public AlarmUser(int id_user_alarm, int id_alarm, int id_user) {
        this.id_user_alarm = id_user_alarm;
        this.id_alarm = id_alarm;
        this.id_user = id_user;
    }

    public AlarmUser(int id_alarm, int id_user) {
        this.id_alarm = id_alarm;
        this.id_user = id_user;
    }

    public int getId_user_alarm() {
        return id_user_alarm;
    }

    public void setId_user_alarm(int id_user_alarm) {
        this.id_user_alarm = id_user_alarm;
    }

    public int getId_alarm() {
        return id_alarm;
    }

    public void setId_alarm(int id_alarm) {
        this.id_alarm = id_alarm;
    }

    public int getId_user() {
        return id_user;
    }

    public void setId_user(int id_user) {
        this.id_user = id_user;
    }

    @Override
    public String toString() {
        return "AlarmUser{" +
                "id_user_alarm=" + id_user_alarm +
                ", id_alarm=" + id_alarm +
                ", id_user=" + id_user +
                '}';
    }
}
