package com.gmproxy.Entities;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.io.Serializable;

/**
 * It's your trusty old entity class. It's not much, but it does what it has to do.
 * Some of these you'll see with two constructors. This is due to not having to insert a id since it's autogenerated.
 */
@Entity(tableName = "medicamentos")
public class Medicine implements Serializable {

    @PrimaryKey
    @ColumnInfo(name = "id_medicamentos")
    Integer id_medicine = 0;

    @ColumnInfo(name = "nombre")
    String medicineName;

    @ColumnInfo(name = "cantidad")
    Integer cantidad = 0;

    @ColumnInfo(name = "id_paciente")
    Integer id_paciente = 0;

    public Medicine(int id_medicine, String medicineName, int cantidad, int id_paciente) {
        this.id_medicine = id_medicine;
        this.medicineName = medicineName;
        this.cantidad = cantidad;
        this.id_paciente = id_paciente;
    }

    public int getId_medicine() {
        return id_medicine;
    }

    public void setId_medicine(int id_medicine) {
        this.id_medicine = id_medicine;
    }

    public String getMedicineName() {
        return medicineName;
    }

    public void setMedicineName(String medicineName) {
        this.medicineName = medicineName;
    }

    public int getCantidad() {
        return cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public int getId_paciente() {
        return id_paciente;
    }

    public void setId_paciente(int id_paciente) {
        this.id_paciente = id_paciente;
    }

    @Override
    public String toString() {
        return "Medicine{" +
                "id_medicine=" + id_medicine +
                ", medicineName='" + medicineName + '\'' +
                ",cantidad=" + cantidad +
                ",id_paciente=" + id_paciente +
                '}';
    }
}
