package com.gmproxy.Entities;

import androidx.room.ColumnInfo;
import androidx.room.Embedded;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Ignore;
import androidx.room.Junction;
import androidx.room.PrimaryKey;
import androidx.room.Relation;

import java.io.Serializable;
import java.util.List;

/**
 * It's your trusty old entity class. It's not much, but it does what it has to do.
 * Some of these you'll see with two constructors. This is due to not having to insert a id since it's autogenerated.
 */
@Entity(tableName = "usuarios_condiciones", foreignKeys = {@ForeignKey(entity = Pathology.class,
        parentColumns = "id_condiciones", childColumns = "id_condiciones"),
        @ForeignKey(entity = User.class,
        parentColumns = "id_usuario", childColumns = "id_usuario")})
public class PathologyUser implements Serializable {

    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id_usuarios_condiciones")
    int id_user_pathology;

    @ColumnInfo(name = "id_usuario")
    Integer id_user = 0;

    @ColumnInfo(name = "id_condiciones")
    Integer id_pathology = 0;

    public class PathologiesWithUser{
        @Embedded
        public Pathology pathology;
        @Relation(
                parentColumn = "id_pathology",
                entityColumn = "id_user",
                associateBy = @Junction(PathologyUser.class)
        ) public List<User> users;
    }

    public class UsersWithPathology{
        @Embedded
        public User user;
        @Relation(
                parentColumn = "id_user",
                entityColumn = "id_pathology",
                associateBy = @Junction(PathologyUser.class)
        ) public List<Pathology> pathologies;
    }

    @Ignore
    public PathologyUser(int id_user_pathology, int id_user, int id_pathology) {
        this.id_user_pathology = id_user_pathology;
        this.id_user = id_user;
        this.id_pathology = id_pathology;
    }

    public PathologyUser(int id_user, int id_pathology) {
        this.id_user = id_user;
        this.id_pathology = id_pathology;
    }

    public int getId_user_pathology() {
        return id_user_pathology;
    }

    public void setId_user_pathology(int id_user_pathology) {
        this.id_user_pathology = id_user_pathology;
    }

    public int getId_user() {
        return id_user;
    }

    public void setId_user(int id_user) {
        this.id_user = id_user;
    }

    public int getId_pathology() {
        return id_pathology;
    }

    public void setId_pathology(int id_pathology) {
        this.id_pathology = id_pathology;
    }

    @Override
    public String toString() {
        return "PathologyUser{" +
                "id_user_pathology=" + id_user_pathology +
                ", id_user=" + id_user +
                ", id_pathology=" + id_pathology +
                '}';
    }
}
