package com.gmproxy.Entities;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.io.Serializable;

/**
 * It's your trusty old entity class. It's not much, but it does what it has to do.
 * Some of these you'll see with two constructors. This is due to not having to insert a id since it's autogenerated.
 */
@Entity(tableName = "condiciones")
public class Pathology implements Serializable {

    @PrimaryKey
    @ColumnInfo(name = "id_condiciones")
    int id_pathology;

    @ColumnInfo(name = "nombreCondicion")
    String pathologyName;

    public Pathology(int id_pathology, String pathologyName) {
        this.id_pathology = id_pathology;
        this.pathologyName = pathologyName;
    }

    public int getId_pathology() {
        return id_pathology;
    }

    public void setId_pathology(int id_pathology) {
        this.id_pathology = id_pathology;
    }

    public String getPathologyName() {
        return pathologyName;
    }

    public void setPathologyName(String pathologyName) {
        this.pathologyName = pathologyName;
    }

    @Override
    public String toString() {
        return "Pathology{" +
                "id_pathology=" + id_pathology +
                ", pathologyName='" + pathologyName + '\'' +
                '}';
    }
}
