package com.gmproxy.Entities;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

import java.io.Serializable;
import java.sql.Blob;

/**
 * It's your trusty old entity class. It's not much, but it does what it has to do.
 * Some of these you'll see with two constructors. This is due to not having to insert a id since it's autogenerated.
 */
@Entity(tableName = "usuarios")
public class User implements Serializable {

    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id_usuario")
    int id_user;

    @ColumnInfo(name = "nombre")
    String user_name;

    @ColumnInfo(name = "apellido")
    String user_surname = "";

    @ColumnInfo(name = "edad")
    String age;


    @ColumnInfo(name = "numHabitacion")
    Integer room_number = 0;

    @NonNull
    @ColumnInfo(name = "genero")
    String gender;

    @ColumnInfo(name = "observaciones")
    String observation;

    @ColumnInfo(name = "imagen", typeAffinity = ColumnInfo.BLOB)
    byte[] user_image;

    @Ignore
    public User(int id_user, String user_name, String user_surname, String age, int room_number, String gender, String observation, byte[] user_image) {
        this.id_user = id_user;
        this.user_name = user_name;
        this.user_surname = user_surname;
        this.age = age;
        this.room_number = room_number;
        this.gender = gender;
        this.observation = observation;
        this.user_image = user_image;
    }

    public User(String user_name, String user_surname, String age, int room_number, String gender, String observation, byte[] user_image) {
        this.user_name = user_name;
        this.user_surname = user_surname;
        this.age = age;
        this.room_number = room_number;
        this.gender = gender;
        this.observation = observation;
        this.user_image = user_image;
    }

    public int getId_user() {
        return id_user;
    }

    public void setId_user(int id_user) {
        this.id_user = id_user;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getUser_surname() {
        return user_surname;
    }

    public void setUser_surname(String user_surname) {
        this.user_surname = user_surname;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }


    public int getRoom_number() {
        return room_number;
    }

    public void setRoom_number(int room_number) {
        this.room_number = room_number;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getObservation() {
        return observation;
    }

    public void setObservation(String observation) {
        this.observation = observation;
    }

    public byte[] getUser_image() {
        return user_image;
    }

    public void setUser_image(byte[] user_image) {
        this.user_image = user_image;
    }

    @Override
    public String toString() {
        return "User{" +
                "id_user=" + id_user +
                ", user_name='" + user_name + '\'' +
                ", user_surname='" + user_surname + '\'' +
                ", age=" + age +
                ", room_number=" + room_number +
                ", gender='" + gender + '\'' +
                ", observation='" + observation + '\'' +
                ", user_image=" + user_image +
                '}';
    }
}
